#pragma once
#include <memory>
#include <vector>

namespace a { struct Node { int x; }; }
namespace b { struct Node { double y; }; }

namespace t
{
    // 1. Same short name in two namespaces: must point to b::Node only.
    struct UsesB { b::Node node; };

    // 2. Type alias hiding the real type: composes a::Node.
    using Nodes = std::vector<a::Node>;
    struct UsesAlias { Nodes nodes; };

    // 3. Class generated by a macro: exists, with member `value`.
#define DECLARE_BOX(Name, T) struct Name { T value; };
    DECLARE_BOX(IntBox, int)

    // 4. CRTP base: inherits from Base<Derived>.
    template <typename D> struct Base { };
    struct Derived : Base<Derived> { };

    // 5. Member through a template alias of a smart pointer: composes a::Node.
    template <typename T> using Owned = std::unique_ptr<T>;
    struct UsesOwned { Owned<a::Node> owned; };

    // 6. Name the extractor cannot see from inside the class: `Node` resolved
    //    via a using-declaration to a::Node.
    using a::Node;
    struct UsesUsingDecl { Node* node; };
}
