#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <optional>

#include "services/cpp_class_extractor.h"

#include "test_support.h"

// The six hard cases of the extraction experiment (tricky/ in
// .development/reference/technical/code-graph-extraction/), each with its known
// answer, then one rule of the resolver per test. Sources are written to a
// real tmpdir and read back, as the extractor does on a project.

using namespace dev_dash;
using core::MemberAccess;
using core::RelationKind;
using services::CppClassExtractor;
using dev_dash::tests::TempDir;
using dev_dash::tests::WriteFile;

namespace
{
    struct Extraction
    {
        TempDir root{"extractor"};
        services::ExtractionResult result;

        explicit Extraction(const std::string& header, const std::string& source = "")
        {
            WriteFile(root.Path() / "src" / "code.h", header);
            if (!source.empty())
                WriteFile(root.Path() / "src" / "code.cpp", source);
            result = CppClassExtractor().Extract(root.Path());
        }

        const core::CodeClass* Class(const std::string& name) const
        {
            const auto& classes = result.model.classes;
            const auto it = std::find_if(classes.begin(), classes.end(),
                                         [&](const core::CodeClass& c) { return c.qualifiedName == name; });
            return it == classes.end() ? nullptr : &*it;
        }

        std::optional<core::CodeRelation> Relation(const std::string& from, const std::string& to) const
        {
            for (const core::CodeRelation& relation : result.model.relations)
                if (relation.from == from && relation.to == to)
                    return relation;
            return std::nullopt;
        }

        bool HasRelation(const std::string& from, const std::string& to, RelationKind kind) const
        {
            const std::optional<core::CodeRelation> relation = Relation(from, to);
            return relation && relation->kind == kind;
        }

        const core::CodeMember* Member(const std::string& className, const std::string& member) const
        {
            const core::CodeClass* cls = Class(className);
            if (cls == nullptr)
                return nullptr;
            const auto it = std::find_if(cls->members.begin(), cls->members.end(),
                                         [&](const core::CodeMember& m) { return m.name == member; });
            return it == cls->members.end() ? nullptr : &*it;
        }
    };

    const std::string kTricky = R"(#pragma once
#include <memory>
#include <vector>

namespace a { struct Node { int x; }; }
namespace b { struct Node { double y; }; }

namespace t
{
    struct UsesB { b::Node node; };

    using Nodes = std::vector<a::Node>;
    struct UsesAlias { Nodes nodes; };

#define DECLARE_BOX(Name, T) struct Name { T value; };
    DECLARE_BOX(IntBox, int)

    template <typename D> struct Base { };
    struct Derived : Base<Derived> { };

    template <typename T> using Owned = std::unique_ptr<T>;
    struct UsesOwned { Owned<a::Node> owned; };

    using a::Node;
    struct UsesUsingDecl { Node* node; };
}
)";
}

TEST_CASE("hard case 1: the same short name in two namespaces", "[extractor]")
{
    Extraction e(kTricky);
    CHECK(e.HasRelation("t::UsesB", "b::Node", RelationKind::kComposes));
    CHECK_FALSE(e.Relation("t::UsesB", "a::Node"));
}

TEST_CASE("hard case 2: a type alias is expanded", "[extractor]")
{
    Extraction e(kTricky);
    CHECK(e.HasRelation("t::UsesAlias", "a::Node", RelationKind::kComposes));
}

TEST_CASE("hard case 3: a class generated by a macro stays out (declared limit)", "[extractor]")
{
    Extraction e(kTricky);
    CHECK(e.Class("t::IntBox") == nullptr);
}

TEST_CASE("hard case 4: a CRTP base is found without its template arguments", "[extractor]")
{
    Extraction e(kTricky);
    CHECK(e.HasRelation("t::Derived", "t::Base", RelationKind::kInherits));
}

TEST_CASE("hard case 5: an alias template of a smart pointer owns its argument", "[extractor]")
{
    Extraction e(kTricky);
    CHECK(e.HasRelation("t::UsesOwned", "a::Node", RelationKind::kComposes));
    CHECK_FALSE(e.Relation("t::UsesOwned", "b::Node"));
}

TEST_CASE("hard case 6: a using-declaration names the class", "[extractor]")
{
    Extraction e(kTricky);
    CHECK(e.HasRelation("t::UsesUsingDecl", "a::Node", RelationKind::kAggregates));
    CHECK_FALSE(e.Relation("t::UsesUsingDecl", "b::Node"));
}

TEST_CASE("classes, nested classes and members are read with their access", "[extractor]")
{
    Extraction e(R"(
namespace app
{
    class Engine
    {
    public:
        Engine();
        bool Start(int speed);
        struct Settings { int gears; };
    protected:
        void Tune();
    private:
        float _speed;
    };
}
)");

    REQUIRE(e.Class("app::Engine") != nullptr);
    REQUIRE(e.Class("app::Engine::Settings") != nullptr);
    CHECK(e.Class("app::Engine")->file.filename() == "code.h");

    const core::CodeMember* start = e.Member("app::Engine", "Start");
    REQUIRE(start != nullptr);
    CHECK(start->isMethod);
    CHECK(start->type == "bool");
    CHECK(start->access == MemberAccess::kPublic);

    REQUIRE(e.Member("app::Engine", "Tune") != nullptr);
    CHECK(e.Member("app::Engine", "Tune")->access == MemberAccess::kProtected);

    const core::CodeMember* speed = e.Member("app::Engine", "_speed");
    REQUIRE(speed != nullptr);
    CHECK_FALSE(speed->isMethod);
    CHECK(speed->type == "float");
    CHECK(speed->access == MemberAccess::kPrivate);

    // A struct starts public.
    REQUIRE(e.Member("app::Engine::Settings", "gears") != nullptr);
    CHECK(e.Member("app::Engine::Settings", "gears")->access == MemberAccess::kPublic);
}

TEST_CASE("the way a member holds a class decides the relation", "[extractor]")
{
    Extraction e(R"(
#include <memory>
#include <vector>
namespace m
{
    struct Part {};
    struct Peer {};
    struct Arg {};
    struct Item {};
    struct Owned {};
    struct Holder
    {
        Part part;
        Peer& peer;
        Arg* arg;
        std::vector<Item> items;
        std::unique_ptr<Owned> owned;
        Part Make(const Arg& arg);
        Holder* self;
    };
}
)");

    CHECK(e.HasRelation("m::Holder", "m::Part", RelationKind::kComposes));      // also returned: composes wins
    CHECK(e.HasRelation("m::Holder", "m::Peer", RelationKind::kAggregates));
    CHECK(e.HasRelation("m::Holder", "m::Arg", RelationKind::kAggregates));     // member pointer wins on the parameter
    CHECK(e.HasRelation("m::Holder", "m::Item", RelationKind::kComposes));
    CHECK(e.HasRelation("m::Holder", "m::Owned", RelationKind::kComposes));
    CHECK_FALSE(e.Relation("m::Holder", "m::Holder"));
}

TEST_CASE("a type used only in a signature is a dependency", "[extractor]")
{
    Extraction e(R"(
namespace d
{
    class Result {};
    class Input {};
    class Service
    {
    public:
        Result Run(const Input& input) const;
    };
}
)");

    CHECK(e.HasRelation("d::Service", "d::Result", RelationKind::kDepends));
    CHECK(e.HasRelation("d::Service", "d::Input", RelationKind::kDepends));
}

TEST_CASE("names are looked up from the innermost scope outwards", "[extractor]")
{
    Extraction e(R"(
namespace outer
{
    struct Node {};
    namespace inner
    {
        struct Node {};
        struct UsesInner { Node node; };
    }
    struct UsesOuter { Node node; };
}
)");

    CHECK(e.HasRelation("outer::inner::UsesInner", "outer::inner::Node", RelationKind::kComposes));
    CHECK_FALSE(e.Relation("outer::inner::UsesInner", "outer::Node"));
    CHECK(e.HasRelation("outer::UsesOuter", "outer::Node", RelationKind::kComposes));
}

TEST_CASE("a name two using-directives make ambiguous gives an uncertain relation", "[extractor]")
{
    Extraction e(R"(
namespace a { struct Node {}; }
namespace b { struct Node {}; struct Only {}; }
namespace c
{
    using namespace a;
    using namespace b;
    struct UsesNode { Node node; };
    struct UsesOnly { Only only; };
}
)");

    const std::optional<core::CodeRelation> ambiguous = e.Relation("c::UsesNode", "a::Node");
    REQUIRE(ambiguous);
    CHECK_FALSE(ambiguous->certain);

    const std::optional<core::CodeRelation> unique = e.Relation("c::UsesOnly", "b::Only");
    REQUIRE(unique);
    CHECK(unique->certain);
}

TEST_CASE("a base class outside the project is kept by name", "[extractor]")
{
    Extraction e(R"(
#include <imgui_md.h>
namespace ui { class MarkdownRenderer : public imgui_md {}; }
)");

    CHECK(e.HasRelation("ui::MarkdownRenderer", "imgui_md", RelationKind::kInherits));
}

TEST_CASE("every source file under the root is read, in path order", "[extractor]")
{
    Extraction e("namespace z { struct FromHeader {}; }",
                 "namespace z { struct FromSource { FromHeader header; }; }");

    CHECK(e.result.filesRead == 2);
    CHECK(e.result.partlyReadFiles.empty());
    REQUIRE(e.result.model.classes.size() == 2);
    // code.cpp sorts before code.h.
    CHECK(e.result.model.classes[0].qualifiedName == "z::FromSource");
    CHECK(e.HasRelation("z::FromSource", "z::FromHeader", RelationKind::kComposes));
}

TEST_CASE("hidden and build directories are skipped", "[extractor]")
{
    Extraction e("namespace p { struct Mine {}; }");
    WriteFile(e.root.Path() / "build" / "_deps" / "lib" / "lib.h", "struct Dependency {};");
    WriteFile(e.root.Path() / "cmake-build-debug" / "gen.h", "struct Generated {};");
    WriteFile(e.root.Path() / ".cache" / "x.h", "struct Cached {};");
    WriteFile(e.root.Path() / "src" / "builder" / "b.h", "struct Builder {};");   // not a build tree

    const services::ExtractionResult result = CppClassExtractor().Extract(e.root.Path());
    CHECK(result.filesRead == 2);
    CHECK(result.model.classes.size() == 2);
}

TEST_CASE("a stop request ends the reading early", "[extractor]")
{
    TempDir root{"extractor-stop"};
    WriteFile(root.Path() / "a.h", "struct A {};");

    std::stop_source source;
    source.request_stop();
    const services::ExtractionResult result = CppClassExtractor().Extract(root.Path(), source.get_token());
    CHECK(result.cancelled);
    CHECK(result.filesRead == 0);
    CHECK(result.model.classes.empty());
}

TEST_CASE("a file with a syntax error is listed and still read", "[extractor]")
{
    Extraction e("namespace s { struct Fine { int x; }; struct Broken { int y }; }");

    REQUIRE(e.result.partlyReadFiles.size() == 1);
    CHECK(e.result.partlyReadFiles[0].filename() == "code.h");
    CHECK(e.Class("s::Fine") != nullptr);
}
